import Head from "next/head";
import Image from "next/image";
import {
  Page,
  Navbar,
  Block,
  Button,
  List,
  ListItem,
  BlockTitle,
} from "konsta/react";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Page>
        <Navbar title="My App" />
        <Image
          src="/next.svg"
          alt="Next.js Logo"
          width={180}
          height={37}
          priority
        />
        <Block>
          <p>Here comes my app</p>
        </Block>
        <Block className="space-y-4">
          <p>Here comes the button</p>
          <Button>Action</Button>

          <List>
            <ListItem href="/" title="Home" />
            <ListItem href="/mobile" title="Mobile" />
          </List>
        </Block>
      </Page>
    </>
  );
}
